In [5]:
import numpy as np

l=[1,2,3,4,5]
print(np.array(l))    # numpy array

[1 2 3 4 5]


In [9]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [13]:
a=np.arange(10,50)
print(a)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


In [23]:
arr=np.array([10,20,30,40,50])
arr[[0,-1]]

array([10, 50])

In [27]:
a=np.array([1,2,3])
b=np.array([4,5,6])

print(a*b)


[ 4 10 18]


In [29]:
#method_1
arr=np.array([10,20,30,40,50])
arr[1:4]   #slicing on array

array([20, 30, 40])

In [35]:
#method_2

arr=np.array([10,20,30,40,50])
arr[[1,2,3]] 

array([20, 30, 40])

In [37]:
#reversing the array using slicing
arr[::-1]

array([50, 40, 30, 20, 10])

In [6]:
import numpy as np

arr=np.array([10,20,30,40,50])
arr>25

array([False, False,  True,  True,  True])

In [32]:
arr=np.array([10,20,30,40,50])
arr[arr>20]=0
print(arr)

[10 20  0  0  0]


In [36]:
arr=np.array([10,20,30,40,50])
d=arr[arr>20]
print(d)

[30 40 50]


In [64]:
arr=np.array([10,20,30,40,50])
arr[arr%3==0]=-1   
print(arr)

[10 20 -1 40 50]


In [66]:
arr=np.array([10,20,30,40,50])
print(arr*arr)


[ 100  400  900 1600 2500]


In [68]:
arr=np.array([10,20,30,40,50])
np.min(arr)

10

In [72]:
arr=np.array([10,20,30,40,50])
np.max(arr)

50

In [108]:
a=np.array([1,2,3])
b=np.array([3,2,6])
d=set(a)
e=set(b)
d.intersection(e)

{2, 3}

In [40]:
# Greater than and less than

arr=np.array([10,20,30,40,50])
d=arr[(arr>10) &(arr<25)]
print(d)

[20]


In [77]:
arr=np.array([10,20,30,40,50])
d=arr[arr>30]
print(d[[0,1]])

[40 50]
