In [1]:
import numpy as np
arr=np.array([1,2,3,4,5])
arr

array([1, 2, 3, 4, 5])

In [15]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [21]:
np.arange(10,50)  #here arange()>>value we give will be end 

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

In [23]:
arr=np.array([1,2,3,4,5])
arr[[0,-1]]

array([1, 5])

In [31]:
arr=np.array([1,2,3,4,5])
arr[::-1]

array([5, 4, 3, 2, 1])

In [73]:
a=np.array([10,20,30,40,50])
a[a>25]=0
print(a)

[10 20  0  0  0]


In [103]:
a=np.array([10,20,30,40,50])
d=a[a>20]
print(d)

[30 40 50]


In [105]:
a.min()

10

In [107]:
a.max()

50

In [119]:
a[-1]

50