In [8]:
# ***NumPY ("Numerical Python")***

In [10]:
import  numpy as np


0-D

In [13]:
a=45
print(a)
print(type(a))

45
<class 'int'>


In [23]:
c=45
arr_0=np.array(c)
print(arr_0)
print(type(arr_0))

45
<class 'numpy.ndarray'>


In [21]:
arr_0.ndim    #prints the dimension

0

In [25]:
arr_0.shape

()

1-D

In [48]:
d=[1,12]
arr_1=np.array(d)
print(arr_1)

# here o/p is array  [1 12] from the list[1, 12]

[ 1 12]


In [50]:
arr_1.ndim

1

In [52]:
arr_1.shape   # ( rows , colums)

(2,)

In [34]:
a=[[1,2,3]]   # list of list
arr_2=np.array(a)
print(arr_2)

[[1 2 3]]


In [36]:
arr_2.ndim

2

In [38]:
arr_2.shape   #(1,3) is (1 row, 3 col)

(1, 3)

>>>functions for creating 1D array
syntax: np.arange(start,end,step)


In [101]:
a=np.arange(10)
print(a)

[0 1 2 3 4 5 6 7 8 9]


>>>>linspace 
syntax: np.linespace(start,end,num_of_samples)

In [112]:
np.linspace(1,5,5)

array([1., 2., 3., 4., 5.])

>>>zeros 
syntax: np.zeros(shape)

In [118]:
np.zeros((4),)

array([0., 0., 0., 0.])

>>>>ones
syntax: np.ones(shape)

In [120]:
np.ones((3,))

array([1., 1., 1.])

>>>>random.randint
syntax: np.random.randint(start,end,num_of_samples)


In [126]:
np.random.randint(1,23,7)

array([19, 15, 22, 13,  2, 21,  4])

>>>Accesing elements/Extarcting the values


In [137]:
a=np.arange(1,9)
print(a)


[1 2 3 4 5 6 7 8]


>>>>Accessing single value through indexing

In [139]:
a[1]

2

In [141]:
a[-1]

8

>>>>Accessing multiple value using slicing

In [145]:
a[2:6]

array([3, 4, 5, 6])

>>>>Accessing multiple value using indexing

In [155]:
a[[0,2,5]]

array([1, 3, 6])

>>>>Accessing multiple value using indexing

In [157]:
a=np.array([1,2,3,4,5,6])
a[a%2==0]   # check the t/f condtion and appends in a

array([2, 4, 6])

In [159]:
a=np.arange(1,49)
a[a%3==0]

array([ 3,  6,  9, 12, 15, 18, 21, 24, 27, 30, 33, 36, 39, 42, 45, 48])

>>>Modify the values in numpy
syntax: np.append(array,value)

In [171]:
# add single value in array

a=np.array([1,2,3,4])
print(np.append(a,23))

[ 1  2  3  4 23]


In [177]:
# add multiple values in the array
a=np.array([1,2,3,4])
print(np.append(a,[11,22,33,44]))  #to input more than one value use list ex:[a,23] and [a,[1,2,2]]

[ 1  2  3  4 11 22 33 44]


In [182]:
# replacing a single value in a 1D array
a[0]=21
print(a)

[21  2  3  4]


In [186]:
# replacing multiple value with a single value in  array
a[[1,3]]=15
print(a)

[21 15  3 15]


In [188]:
# replacing multiple value with a multiple value in  array
a[[1,3]]=[12,23]
print(a)

[21 12  3 23]


>>>>delete a single value in array
syntax: np.delete(array,indexnumber)

In [194]:
np.delete(a,0)

array([12, 23])

In [196]:
# delete a multiple value in array

np.delete(a,[0,2])


array([12, 23])

In [198]:
#copy array
a=np.array([1,2,3])
b=a.copy()
b[0]=100
print(a)
print(b)

[1 2 3]
[100   2   3]


In [202]:
# sorting an array
a=np.array([1,4,3,2])
b=np.sort(a)
print(b)


[1 2 3 4]


****operations****
>>>>arithimetic
>>>>comparision
>>>>mathematical

In [240]:
a=np.add(12,123)
print(d)

135


In [242]:
b=a-1
print(b)


134


In [244]:
a=np.array([1,2,3,4])
a+1

array([2, 3, 4, 5])

In [246]:
np.add(12,22)

34

In [230]:
c=a**2  
print(c)

[ 1  4  9 16]


>>>comparision operators

In [248]:
a==b

array([False, False, False, False])

In [250]:
c<=a

array([ True, False, False, False])

>>>mathemactical operations

In [254]:
np.exp(a)

array([ 2.71828183,  7.3890561 , 20.08553692, 54.59815003])

In [256]:
np.log(a)

array([0.        , 0.69314718, 1.09861229, 1.38629436])

In [260]:
import warnings
warnings.simplefilter("ignore")

2D Numpy array

In [264]:
d=np.array([[1,2,3],[23,4,3]])
print(d)

[[ 1  2  3]
 [23  4  3]]


In [266]:
d.ndim

2

In [272]:
d.shape

(2, 3)

In [278]:
#identity matrix
np.eye(3,3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [280]:
#diagonal matrix
np.diag([1,2,3])

array([[1, 0, 0],
       [0, 2, 0],
       [0, 0, 3]])

In [296]:
#diagonal matrix
a=np.array([[1,2,3],[3,4,5]])
print(np.diag(a))

[1 4]


In [290]:
np.diag([1,2,3])

array([[1, 0, 0],
       [0, 2, 0],
       [0, 0, 3]])

In [298]:
a[0]

array([1, 2, 3])

converting nd array to 1D array

In [307]:
a= np.array([[1,2,3],[5,6,7]])
print(a)

b=a.ravel()
print(b)

[[1 2 3]
 [5 6 7]]
[1 2 3 5 6 7]


reshape array

In [309]:
arr = np.arange(6)
print(arr)
print(arr.shape)

[0 1 2 3 4 5]
(6,)


In [311]:
a1=arr.reshape(2,3)
print(a1)

[[0 1 2]
 [3 4 5]]


In [313]:
a=np.array([[0,1,5],[10,50,8]])
print(a)
print(a.shape)

[[ 0  1  5]
 [10 50  8]]
(2, 3)


In [315]:
print(a.reshape(3,2))

[[ 0  1]
 [ 5 10]
 [50  8]]


In [317]:
c= a.T
print(c)

[[ 0 10]
 [ 1 50]
 [ 5  8]]


In [325]:

#sorting along an axis=1 --->row and axis=0-->column
a = np.array([[5,4,6],[2,8,2],[8,9,20]])
b = np.sort(a,axis=0)
b


array([[ 2,  4,  2],
       [ 5,  8,  6],
       [ 8,  9, 20]])

In [335]:
a = np.array([[1,2],[3,4],[5,6]])
b = np.array([[40,4],[24,14],[55,36]])
print(a+b)

[[41  6]
 [27 18]
 [60 42]]


In [347]:
c = np.array([[1,2],[3,4],[5,6]])
d = np.array([[40,4],[24,14],[55,36]])
np.matmul(c,d)

ValueError: matmul: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature (n?,k),(k,m?)->(n?,m?) (size 3 is different from 2)

In [349]:
np.concatenate((a,b),axis=0)

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [40,  4],
       [24, 14],
       [55, 36]])

In [351]:
#vertical stack
np.vstack((a,b))

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [40,  4],
       [24, 14],
       [55, 36]])

In [353]:
#horizontal stack
np.hstack((a,b))

array([[ 1,  2, 40,  4],
       [ 3,  4, 24, 14],
       [ 5,  6, 55, 36]])